### ISSUE TITLE
request for pyalsaaudio / python-alsaaudio support

### ISSUE THREAD

**Issue by clach04** [gcwnow/buildroot#1]
If we have http://pyalsaaudio.sourceforge.net/ (in the same way there is PyGame support in https://github.com/gcwnow/buildroot/tree/opendingux-2012.08/package/python-pygame) we could record audio from Python.

With pyalsaaudio support , microphones testing could be added to https://bitbucket.org/clach04/hwtest/wiki/Home

**Comment by pcercuei** [comment]
I doubt this is really useful for anything but the hwtest; in this case you could just pack the Python module with the app.
