### ISSUE TITLE
cant build from a directory with spaces in the name

### ISSUE THREAD

**Issue by RodrigoCard** [gcwnow/buildroot#11]
The title is self-explanatory. :)

**Comment by mthuurne** [comment]
I added a note to the wiki to alert people to this problem. Thanks for reporting it.

Which package breaks? If it's an OpenDingux specific package, we'll fix it, but if Buildroot in general won't build in paths containing spaces, then I don't want to spend a potentially large amount of time on fixing that.

**Comment by RodrigoCard** [comment]
This is all the output I got when running "sudo make menuconfig":

make: execvp: /Users/Rodrigo/Workspace: Permission denied
/Users/Rodrigo/Workspace:1: warning: NUL character seen; rest of line ignored
/Users/Rodrigo/Workspace:1: **\* missing separator.  Stop.

the full path was "/Users/Rodrigo/Workspace 2/"

**Comment by mthuurne** [comment]
It seems GNU Make doesn't like spaces in path names: http://savannah.gnu.org/bugs/?712
Since Buildroot is largely implemented in Make, there is nothing we can do about this, so I'm closing this bug.
