### ISSUE TITLE
Enabling linkdev's 'alternate key mapping' input method causes SDL 2.0 to issue unrecognized keypress messages

### ISSUE THREAD

**Issue by senquack** [gcwnow/buildroot#12]
This behavior does not occur with the public 8-20-2014 firmware, only with newer unreleased beta firmware dated 2014-11-23. SDL 1.2 behaves the same as the old firmware. SDL 2.0 does not, however:

From the command line, use opkrun to run Nebuleon's SDL2.0 version of his input tester: 'opkrun  -m jstester-2.gcw0.desktop input-test.opk'      Alternatively, run a SDL2.0 app directly from the command line after issuing following command: echo Y > /sys/devices/platform/linkdev/alt_key_map

Any button presses, excluding the DPAD, will cause the following message to show on stdout:
'INFO: The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL mailing list sdl@libsdl.org EVDEV KeyCode 3XX' Where 3XX corresponds to each unique button press.

Despite these messages, the alternate key-to-joy-event mapping is indeed functioning.  If you disable the key-to-joy-event mapping, SDL does not report these errors and receives SDL_KEYUP/SDL_KEYDOWN events from the buttons, as normal, with no complaints of unrecognized evdev keycodes.

**Comment by pcercuei** [comment]
Fixed: https://github.com/pcercuei/SDL2/commit/f09096ef9d8b0ede54e51bbb02d09af1efa0e74f
